# Generated by Django 5.0.1 on 2024-11-07 15:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='Название')),
                ('determinants', models.CharField(max_length=32, verbose_name='Детерминаторы')),
                ('personal', models.BooleanField(default=True, verbose_name='Личный')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='Название')),
                ('positions', models.CharField(max_length=64, verbose_name='Позиции')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('en', 'en'), ('ru', 'ru')], default='ru', max_length=2, verbose_name='Язык')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('determinants', models.CharField(blank=True, max_length=32, verbose_name='Детерминаторы')),
                ('type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.blocktype', verbose_name='Тип блока')),
            ],
        ),
        migrations.AddField(
            model_name='blocktype',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.category', verbose_name='Категория'),
        ),
    ]
