# Generated by Django 5.0.1 on 2024-11-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
        migrations.AlterModelOptions(
            name='blocktype',
            options={'ordering': ['order'], 'verbose_name': 'Тип Блоков', 'verbose_name_plural': 'Типы Блоков'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='blocktype',
            name='order',
            field=models.SmallIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.SmallIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='positions',
            field=models.CharField(blank=True, max_length=64, verbose_name='Позиции'),
        ),
    ]
