# Generated by Django 5.0.1 on 2024-11-07 20:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_block_options_alter_blocktype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='Название')),
                ('code', models.CharField(max_length=8, verbose_name='Код')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
            },
        ),
        migrations.AlterModelOptions(
            name='blocktype',
            options={'ordering': ['category__order', 'order'], 'verbose_name': 'Тип Блоков', 'verbose_name_plural': 'Типы Блоков'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='block',
            name='determinants',
        ),
        migrations.RemoveField(
            model_name='block',
            name='language',
        ),
        migrations.AlterUniqueTogether(
            name='blocktype',
            unique_together={('order', 'category')},
        ),
        migrations.AddField(
            model_name='block',
            name='arcane',
            field=models.SmallIntegerField(default=0, verbose_name='Аркан'),
        ),
        migrations.AddField(
            model_name='blocktype',
            name='positions',
            field=models.CharField(blank=True, max_length=32, verbose_name='Позиции'),
        ),
        migrations.AlterField(
            model_name='block',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='data.blocktype', verbose_name='Тип блока'),
        ),
        migrations.AlterField(
            model_name='blocktype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_types', to='data.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.SmallIntegerField(default=1, unique=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='positions',
            field=models.CharField(blank=True, max_length=48, verbose_name='Позиции'),
        ),
        migrations.RemoveField(
            model_name='blocktype',
            name='determinants',
        ),
    ]
