# Generated by Django 5.0.1 on 2024-11-12 17:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_program_alter_blocktype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='Название')),
                ('arcane', models.CharField(max_length=2, verbose_name='Аркан')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Личный бренд',
                'verbose_name_plural': 'Личные бренды',
            },
        ),
    ]
