# Generated by Django 5.0.1 on 2024-11-15 20:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_forecast_prevlife_scenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sexiness',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=8, verbose_name='Код')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Сексуальность',
                'verbose_name_plural': 'Сексуальности',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['type__category__order', 'type__order', 'arcane'], 'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['arcane'], 'verbose_name': 'Личный бренд', 'verbose_name_plural': 'Личные бренды'},
        ),
        migrations.AlterModelOptions(
            name='forecast',
            options={'ordering': ['arcane'], 'verbose_name': 'Прогноз', 'verbose_name_plural': 'Прогнозы'},
        ),
        migrations.AlterModelOptions(
            name='prevlife',
            options={'ordering': ['code'], 'verbose_name': 'Предедущая жизнь', 'verbose_name_plural': 'Предедущая жизнь'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['code'], 'verbose_name': 'Программа', 'verbose_name_plural': 'Программы'},
        ),
        migrations.AlterModelOptions(
            name='scenario',
            options={'ordering': ['code'], 'verbose_name': 'Сценарий Жизни', 'verbose_name_plural': 'Сценарии Жизни'},
        ),
        migrations.AlterField(
            model_name='blocktype',
            name='title',
            field=models.CharField(blank=True, max_length=64, verbose_name='Название'),
        ),
    ]
