# Generated by Django 5.0.1 on 2024-11-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_category_options_category_solo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.SmallIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='solo',
            field=models.BooleanField(default=True, verbose_name='Одиночная матрица'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('solo', 'order')},
        ),
    ]
