# Generated by Django 5.0.1 on 2024-11-17 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_category_order_alter_category_solo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['type__category__solo', 'type__category__order', 'type__order', 'arcane'], 'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
        migrations.AlterModelOptions(
            name='blocktype',
            options={'ordering': ['category__solo', 'category__order', 'order'], 'verbose_name': 'Тип Блоков', 'verbose_name_plural': 'Типы Блоков'},
        ),
    ]
