# Generated by Django 5.0.1 on 2024-11-24 16:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_alter_block_options_alter_blocktype_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=32, verbose_name='Название')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('code', models.CharField(max_length=10, verbose_name='Код')),
                ('type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_blocks', to='data.blocktype', verbose_name='Тип блока')),
            ],
            options={
                'verbose_name': 'Блок с кодом',
                'verbose_name_plural': 'Блоки с кодом',
                'ordering': ['type__category__order', 'code'],
            },
        ),
    ]
