# Generated by Django 5.0.1 on 2024-11-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_codeblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocktype',
            name='for_codes',
            field=models.BooleanField(default=False, verbose_name='Для блоков с кодом'),
        ),
    ]
