# Generated by Django 5.0.1 on 2024-11-24 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_blocktype_for_codes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forecast',
        ),
        migrations.DeleteModel(
            name='PrevLife',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='Scenario',
        ),
        migrations.DeleteModel(
            name='Sexiness',
        ),
    ]
