# Generated by Django 5.0.1 on 2024-11-27 20:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_delete_forecast_delete_prevlife_delete_program_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('suit', models.CharField(choices=[('M', 'Старшие арканы'), ('C', 'Чаш'), ('P', 'Пентаклей'), ('S', 'Мечей'), ('W', 'Жезлов')], default='M', max_length=1, verbose_name='Масть')),
                ('rank', models.CharField(choices=[('0', 'Аркан'), ('A', 'Туз'), ('2', 'Двойка'), ('3', 'Тройка'), ('4', 'Четверка'), ('5', 'Пятерка'), ('6', 'Шестерка'), ('7', 'Семерка'), ('8', 'Восьмерка'), ('9', 'Девятка'), ('1', 'Десятка'), ('P', 'Паж'), ('N', 'Рыцарь'), ('Q', 'Королева'), ('K', 'Король')], default='0', max_length=1, verbose_name='Стоимость')),
                ('arcane', models.SmallIntegerField(default=0, verbose_name='Аркан')),
                ('desc', models.TextField(blank=True, verbose_name='Описание')),
                ('meaning1', models.TextField(blank=True, verbose_name='Прямое значение')),
                ('explanation1', models.TextField(blank=True, verbose_name='Прямое толкование')),
                ('meaning2', models.TextField(blank=True, verbose_name='Перевернутое значение')),
                ('explanation2', models.TextField(blank=True, verbose_name='Перевернутое толкование')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
                'ordering': ['suit', 'rank', 'arcane'],
                'unique_together': {('suit', 'rank', 'arcane')},
            },
        ),
    ]
