# Generated by Django 5.0.1 on 2024-11-27 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_card'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='card',
            unique_together=set(),
        ),
    ]
