# Generated by Django 5.0.1 on 2024-11-27 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_alter_card_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('suit', 'rank', 'arcane')},
        ),
    ]
