# Generated by Django 5.0.1 on 2024-11-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_alter_card_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Карта', 'verbose_name_plural': 'Карты'},
        ),
    ]
