# Generated by Django 5.0.1 on 2024-12-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_alter_card_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='Картинка'),
        ),
    ]
