# Generated by Django 5.0.1 on 2024-12-14 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_alter_card_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='image',
        ),
    ]
