# Generated by Django 5.0.1 on 2024-11-24 19:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField(default=1, verbose_name='Порядок')),
                ('positive', models.BooleanField(default=True, verbose_name='Позитивная')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('arcane', models.SmallIntegerField(default=0, verbose_name='Аркан')),
                ('used', models.BooleanField(default=False, verbose_name='Использована')),
            ],
            options={
                'verbose_name': 'Энергия',
                'verbose_name_plural': 'Энергии',
                'ordering': ['positive', 'arcane', 'order'],
                'unique_together': {('positive', 'arcane', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Minor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField(default=1, verbose_name='Порядок')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('suit', models.CharField(choices=[('C', 'Чаш'), ('S', 'Мечей'), ('W', 'Жезлов'), ('P', 'Пентаклей')], max_length=1, verbose_name='Масть')),
                ('rank', models.CharField(choices=[('A', 'Туз'), ('2', 'Двойка'), ('3', 'Тройка'), ('4', 'Четверка'), ('5', 'Пятерка'), ('6', 'Шестерка'), ('7', 'Семерка'), ('8', 'Восьмерка'), ('9', 'Девятка'), ('1', 'Десятка'), ('P', 'Паж'), ('N', 'Рыцарь'), ('Q', 'Королева'), ('K', 'Король')], max_length=1, verbose_name='Стоимость')),
                ('used', models.BooleanField(default=False, verbose_name='Использована')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
                'ordering': ['suit', 'rank', 'order'],
                'unique_together': {('suit', 'rank', 'order')},
            },
        ),
    ]
