# Generated by Django 5.0.1 on 2024-11-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minor',
            name='suit',
            field=models.CharField(choices=[('C', 'Чаш'), ('P', 'Пентаклей'), ('S', 'Мечей'), ('W', 'Жезлов')], max_length=1, verbose_name='Масть'),
        ),
    ]
