# Generated by Django 5.0.1 on 2024-12-02 20:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_delete_energy_delete_minor_alter_prediction_options'),
        ('user', '0012_remove_user_allows_write_to_pm_remove_user_blocked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('price', models.SmallIntegerField(default=100, verbose_name='Стоимость (в звездах)')),
                ('finalised', models.BooleanField(default=False, verbose_name='Окончена')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='user.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
    ]
