# Generated by Django 5.0.1 on 2024-10-23 18:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bot', models.BooleanField(default=False, verbose_name='Бот')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='Имя пользователя @')),
                ('language_code', models.CharField(default='en', max_length=2, verbose_name='Язык')),
                ('added_to_attachment_menu', models.BooleanField(default=False, verbose_name='Добавил в меню прикрепленных')),
                ('allows_write_to_pm', models.BooleanField(default=True, verbose_name='Разрешил ему писать')),
                ('chat_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='ID чата')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='MatrixRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('gender', models.CharField(choices=[('m', 'парень'), ('f', 'девушка')], max_length=1, verbose_name='Гендер')),
                ('date', models.CharField(max_length=10, verbose_name='Дата рождения')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('paired', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.matrixrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос по матрице',
                'verbose_name_plural': 'Запросы по матрице',
                'ordering': ['created'],
            },
        ),
    ]
