# Generated by Django 5.0.1 on 2024-10-30 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_master_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='master',
        ),
        migrations.RemoveField(
            model_name='session',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Master',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
