# Generated by Django 5.0.1 on 2024-10-30 20:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_session_master_remove_session_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('monday_hours', models.CharField(blank=True, max_length=32, verbose_name='Рабочие часы в пн')),
                ('tuesday_hours', models.CharField(blank=True, max_length=32, verbose_name='Рабочие часы в вт')),
                ('wednesday_hours', models.CharField(blank=True, max_length=32, verbose_name='Рабочие часы в ср')),
                ('thursday_hours', models.CharField(blank=True, max_length=32, verbose_name='Рабочие часы в чт')),
                ('friday_hours', models.CharField(blank=True, max_length=32, verbose_name='Рабочие часы в пт')),
                ('saturday_hours', models.CharField(blank=True, max_length=32, verbose_name='Рабочие часы в сб')),
                ('sunday_hours', models.CharField(blank=True, max_length=32, verbose_name='Рабочие часы в вс')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user', verbose_name='аккаунт')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('A', 'Материальное'), ('B', 'Самочувствие'), ('C', 'Отношения')], max_length=1, verbose_name='План')),
                ('online', models.BooleanField(verbose_name='Онлайн')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('status', models.CharField(choices=[('O', 'Заказана'), ('A', 'Одобрена'), ('S', 'Начата'), ('F', 'Окончена')], max_length=1, verbose_name='Статус')),
                ('paid', models.BooleanField(verbose_name='Оплачена')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user', verbose_name='покупатель')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.master', verbose_name='мастер')),
            ],
            options={
                'verbose_name': 'Сессия',
                'verbose_name_plural': 'Сессии',
            },
        ),
    ]
