# Generated by Django 5.0.1 on 2024-10-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_master_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='name',
            field=models.CharField(default='', max_length=32, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
