# Generated by Django 5.1.2 on 2024-11-01 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_master_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="master",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.user",
                verbose_name="аккаунт",
            ),
        ),
    ]
