# Generated by Django 5.0.1 on 2024-11-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_master_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='added_to_attachment_menu',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=32, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=32, verbose_name='Фамилия'),
        ),
    ]
