# Generated by Django 5.0.1 on 2024-11-07 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_user_added_to_attachment_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrixrequest',
            name='paired',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pair', to='user.matrixrequest'),
        ),
        migrations.AlterField(
            model_name='matrixrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='user.user', verbose_name='Пользователь'),
        ),
    ]
