# Generated by Django 5.0.1 on 2024-11-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_matrixrequest_paired_matrixrequest_date2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked',
            field=models.BooleanField(default=False, verbose_name='Заблокирован'),
        ),
    ]
