# Generated by Django 5.0.1 on 2024-11-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language_code',
            field=models.CharField(default='ru', max_length=2, verbose_name='Язык'),
        ),
    ]
