# Generated by Django 5.0.1 on 2024-12-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_language_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='allows_write_to_pm',
        ),
        migrations.RemoveField(
            model_name='user',
            name='blocked',
        ),
        migrations.RemoveField(
            model_name='user',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_bot',
        ),
        migrations.AddField(
            model_name='user',
            name='questions',
            field=models.SmallIntegerField(default=0, verbose_name='Баланс вопросов'),
        ),
    ]
