# Generated by Django 5.0.1 on 2024-12-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_user_allows_write_to_pm_remove_user_blocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_action',
            field=models.TextField(default='/start', verbose_name='Последнее действие'),
        ),
    ]
