# Generated by Django 5.0.1 on 2024-12-06 17:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_user_last_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matrixrequest',
            options={'ordering': ['-created'], 'verbose_name': 'Запрос по матрице', 'verbose_name_plural': 'Запросы по матрице'},
        ),
        migrations.CreateModel(
            name='ReferralLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_link', to='user.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Реферальная ссылка',
                'verbose_name_plural': 'Реферальные ссылки',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='joined_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='user.referrallink', verbose_name='Присоеденился по ссылке'),
        ),
    ]
