# Generated by Django 5.0.1 on 2024-12-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_session_options_alter_user_joined_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=32, verbose_name='Имя пользователя @'),
        ),
    ]
