# Generated by Django 5.2.4 on 2025-07-30 08:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='master',
        ),
        migrations.RemoveField(
            model_name='referrallink',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='joined_by',
        ),
        migrations.RemoveField(
            model_name='session',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='questions',
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Master',
        ),
        migrations.DeleteModel(
            name='ReferralLink',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
